services:
  - type: web
    name: labelqcchecker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: FLASK_ENV
        value: production